import express from "express";
import cors from "cors";
import "dotenv/config";
import { rutasIdentidad } from "./api/rutas/identidad.js";
import { rutasAcademico } from "./api/rutas/academico.js";
import { rutasMatricula } from "./api/rutas/matricula.js";
import { rutasPagos } from "./api/rutas/pagos.js";
import { rutasHorarios } from "./api/rutas/horarios.js";
import { rutasAsistencia } from "./api/rutas/asistencia.js";
import { rutasProfesores } from "./api/rutas/profesores.js";
import { rutasEventos } from "./api/rutas/eventos.js";
import { rutasAvances } from "./api/rutas/avances.js";
import { rutasContabilidad } from "./api/rutas/contabilidad.js";
import { rutasComunicacion } from "./api/rutas/comunicacion.js";
import { rutasInventario } from "./api/rutas/inventario.js";
import { rutasPermisos } from "./api/rutas/permisos.js";
import { rutasReportes } from "./api/rutas/reportes.js";
import { rutasPensum } from "./api/rutas/pensum.js";
import { rutasAuditoria } from "./api/rutas/auditoria.js";
import { manejoErrores, respuestaExitosa } from "./api/middlewares/manejoErrores.js";
const app = express();
app.use(cors());
app.use(express.json());
app.get("/api/salud", (req, res) => respuestaExitosa(res, { estado: "ok", fase: "0 - core arquitectonico" }));
app.use("/api/identidad", rutasIdentidad);
app.use("/api/academico", rutasAcademico);
app.use("/api/matricula", rutasMatricula);
app.use("/api/pagos", rutasPagos);
app.use("/api/horarios", rutasHorarios);
app.use("/api/asistencia", rutasAsistencia);
app.use("/api/profesores", rutasProfesores);
app.use("/api/eventos", rutasEventos);
app.use("/api/avances", rutasAvances);
app.use("/api/contabilidad", rutasContabilidad);
app.use("/api/comunicacion", rutasComunicacion);
app.use("/api/inventario", rutasInventario);
app.use("/api/permisos", rutasPermisos);
app.use("/api/reportes", rutasReportes);
app.use("/api/pensum", rutasPensum);
app.use("/api/auditoria", rutasAuditoria);
app.use(manejoErrores);
if (process.env.VERCEL !== "1") {
  const PUERTO = process.env.PUERTO || 3001;
  app.listen(PUERTO, () => console.log(`Backend Jacquin escuchando en puerto ${PUERTO}`));
}
export default app;
